Add "report source" functionality #53
brendt/aggregate.stitcher.io pull request #108
Opened 2020-11-14 10:42 UTC by benboubekeur

- Logged in users should be able to report a source
-   the "Report source" link should be in line with the "Mute source" link
-  Clicking the link brings you to a new page, before filing a report there's a required text area
-  Reports should be shown in the /admin/sources overview, ideally with a filter just like the "Show only inactive sources" filter
-  Admins should be able to read all reports for a source on that source's detail page

2020-11-19 04:58 UTC, brendt commented
Thanks! You can target this towards master btw :) Could you take a look at the merge conflicts?

2020-11-19 05:04 UTC, brendt requested changes
Already looking good! I've got a few remarks. There are also some code style things I'd do differently, but I'll fix those when I've merged this in master.

Since you started your branch, I updated Laravel; which means that the `spatie/blade-x` package was replaced by native Laravel blade components. The only things that should change is making sure all blade component files are `kebab-cased` and that components are prefixed with an `x`, eg `x-sort-link` instead of `sort-link`.

2020-11-19 05:04 UTC, brendt commented on database/migrations/2020_11_06_160152_create_spams_table.php
> +        Schema::create('spams', function (Blueprint $table) {
I'd call it `post_reports`, and the model `PostReport`

2020-11-19 05:04 UTC, brendt commented on database/migrations/2020_11_13_182002_add_report_field_to_spams_table.php
> +class AddReportFieldToSpamsTable extends Migration
You can combine this with the original migration

2020-11-20 15:12 UTC, benboubekeur commented on app/Domain/Post/Models/Post.php
> +        return $this->hasMany(Spam::class);
Php storm was confused probably when refactoring !

2020-11-24 04:47 UTC, brendt commented
Hey @benboubekeur I still think there's something wrong with your commit history: it lists all preview commits as well in the PR.

2020-11-24 07:49 UTC, benboubekeur commented
So i should squash them ?

2020-11-24 09:01 UTC, brendt commented
You can try that, have you rebased on master?

2020-11-24 09:06 UTC, benboubekeur commented
Yes i did that :

- i will create a new branch locally with feature name

- Push that branch 

-  Create a new PR because it's messy now

2020-11-24 10:13 UTC, brendt commented
Ok let's continue in the other PR

2020-11-24 10:13 UTC, closed without merging